# Generated by Django 2.2.6 on 2020-07-14 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pas', models.CharField(max_length=10)),
                ('accoun_balanch', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('fromm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SENDER', to='main.User')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RECIEVER', to='main.User')),
                ('typeof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneytype', to='main.MoneyType')),
            ],
        ),
        migrations.AddField(
            model_name='moneytype',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
