# Generated by Django 2.2.6 on 2020-12-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201215_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='accoun_balanch',
            new_name='account_balanch',
        ),
    ]
