# Generated by Django 2.2.6 on 2020-12-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201215_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='account_balanch',
            new_name='account_balance',
        ),
    ]
