# Generated by Django 2.2.6 on 2020-12-18 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201218_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transiction',
            name='fromm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SENDER', to='main.CustomUser'),
        ),
        migrations.AlterField(
            model_name='transiction',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RECIEVER', to='main.CustomUser'),
        ),
    ]
