# Generated by Django 2.2.6 on 2020-12-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201218_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transiction',
            old_name='to',
            new_name='reciever',
        ),
        migrations.RenameField(
            model_name='transiction',
            old_name='fromm',
            new_name='sender',
        ),
    ]
